{{- if .Values.storageClass.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.storageClass.serverIP | required "A valid .Values.storageClass.serverIP is required!" }}
  share: / # We use fsid=0 so the root export is /
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
  mountPermissions: "0777"
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: Immediate
mountOptions:
  {{- range .Values.storageClass.mountOptions }}
  - {{ . }}
  {{- end }}
{{- end }}
